server:
  port: 8082

spring:
  application:
    name: Server-Provider

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}

info:
  app.name: alex
  company.name: test
  build.artifactId: $project.artifactId$
  build.version: $project.version$



